### ISSUE TITLE
Show email value in event log when debugging mail issue

### ISSUE THREAD

**Issue by johnzastrow** [mantisbt-plugins/EventLog#1]
Trying to debug email, the event log is one of the only logs I can see. 

I'm getting "[mail] ERROR: Message could not be sent - Invalid address: 1" in the event log, but I'd really like to be able to see the offending value... in this case the problematic email address I guess.

**Comment by vboctor** [comment]
Please open a bug on http://www.mantisbt.org/bugs to enhance the logging in this case.  This is not a change on the Eventlog plugin side.
